apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: ghcr.io/DongaNiharika14/gitops-demo-app
    newName: ghcr.io/DongaNiharika14/gitops-demo-app
    newTag: latest # promoted manually via PR after validating in dev

replicas:
  - name: gitops-demo-app
    count: 4
