apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/DongaNiharika14/cicd-gitops-eks.git
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true # remove resources that are no longer defined in Git
      selfHeal: true # revert any manual/out-of-band changes back to Git state
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
