apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: ghcr.io/DongaNiharika14/gitops-demo-app
    newName: ghcr.io/DongaNiharika14/gitops-demo-app
    newTag: latest

replicas:
  - name: gitops-demo-app
    count: 2
